### ISSUE TITLE
Indication if the item is open-source

### ISSUE THREAD

**Issue by williamboman** [iCHAIT/awesome-osx#10]
I thought it would be nice to have some kind of indication if a listed item is OSS (which is very important to some users).

I've put up a [branch](https://github.com/williamboman/awesome-osx/tree/add-OSS-logo) where open-source items are flagged with the [OSI](http://opensource.org/) logo (the choice of logo is purely out of laziness). Thoughts?

**Comment by dufferzafar** [comment]
This would be a nice addition. :+1:

**Comment by dufferzafar** [comment]
@williamboman I think you should just go ahead and open a pull :)

**Comment by williamboman** [comment]
@dufferzafar There are a lot of items in the list that are open-source, but not tagged yet. Before going through each item I'd like to know if this is interesting to @iCHAIT at all :smile:.

**Comment by iCHAIT** [comment]
@williamboman Yeah, I like it, it would be a nice addition :smiley:

My only concern here is that what kind of logo would we want for this sort of segregation.

What do you guys think?

**Comment by williamboman** [comment]
Also, the markup will get quite messy with the custom, 106 character long `<img />` tag. Does anyone know a better way to mark it up (with Retina support)?

**Comment by williamboman** [comment]
@iCHAIT 
> My only concern here is that what kind of logo would we want for this sort of segregation.

I think the OSI logo is pretty universal, but something feels off about using it here. If anyone wants to make a custom one, that'd be cool.

**Comment by iCHAIT** [comment]
@williamboman I agree with you, I think we should have this, and as you very rightly mentioned as it is very much universal it would just fit perfectly here.

I think you can proceed with this.

:+1:

**Comment by iCHAIT** [comment]
BTW, I think we should find a way for managing the `<img />` it would really make things complicated.

**Comment by williamboman** [comment]
>BTW, I think we should find a way for managing the <img /> it would really make things complicated.

Definitely.

Which do you guys prefer, first or second? (logo position)
![screenshot 2015-09-11 at 17 44 18](https://cloud.githubusercontent.com/assets/6705160/9819177/cc03b5d4-58ac-11e5-9705-907c412078d9.png)

**Comment by iCHAIT** [comment]
Second!

**Comment by dufferzafar** [comment]
Yeah, second is better.

**Comment by williamboman** [comment]
Opened a PR now. About the `<img />` issue, I just resized the logo to `14x14` and include it markdown-style, which is much shorter (no Retina support though :cry:).
