### ISSUE TITLE
Mac-Dev-Setup

### ISSUE THREAD

**Issue by harshasrinivas** [iCHAIT/awesome-osx#136]
[**This repository**](https://github.com/nicolashery/mac-dev-setup) is pretty good. Do have a look at it.
I think this could be added to the **SETUP** category.

And btw, great work! :smile:

**Comment by iCHAIT** [comment]
@harshasrinivas Yup, was already aware of this, will give a though on to how to include this in the list, glad you liked it :)

**Comment by harshasrinivas** [comment]
:+1:
