### ISSUE TITLE
Adium for chat apps?

### ISSUE THREAD

**Issue by arun057** [iCHAIT/awesome-osx#143]

**Comment by nclements** [comment]
Refer to this [pull](https://github.com/iCHAIT/awesome-osx/pull/26) request (and probably a few others).

**Comment by herrbischoff** [comment]
I agree with the PR contents and @nclements. Adium is quickly becoming obsolete as people are either using an IRC client or Slack/HipChat/whathaveyou.

On a side note, I just realized that personally I do not know a single person who's using AIM/ICQ/Yahoo accounts for chatting. And whoever uses Facebook messaging is beyond help anyway. ;P

**Comment by iCHAIT** [comment]
@herrbischoff  Actually I still use Adium, don't know if I am to lazy to install some other chat client or if I am too attached to it :p
