### ISSUE TITLE
El Capitan 10.11 Clean Install, Setup Lists

### ISSUE THREAD

**Issue by shaun10** [iCHAIT/awesome-osx#156]
All do you think it would be fitting to start adding OS X 10.11 setup notes and gist articles to the project? I found a good Gist article at:

https://gist.github.com/saetia/1623487

Let me know if it is sufficiently comprehensive and I can work on the pull request.

**Comment by iCHAIT** [comment]
Looks good to me, but is there anything else you are planning to add along with this gist?

P.S. Open a PR for this. (Under the setup section.)

**Comment by shaun10** [comment]
Ok thanks Chaitanya! I submitted the pull request.
