### ISSUE TITLE
ADD TO AWESOME

### ISSUE THREAD

**Issue by nickedes** [iCHAIT/awesome-osx#2]
You should add your repo's link [here](https://github.com/sindresorhus/awesome) as [Mac](https://github.com/iCHAIT/awesome-mac) over [here](https://github.com/sindresorhus/awesome#platforms) .

**Comment by iCHAIT** [comment]
Yeah. it is definitely on the cards, but it is not ready as of now. Hopefully this can get there sooner than later.

**Comment by nickedes** [comment]
:+1:
