### ISSUE TITLE
Add 'free' icon?

### ISSUE THREAD

**Issue by briatte** [iCHAIT/awesome-osx#286]
May I suggest adding a little icon to all freeware? That'd be useful for those who (try to) focus their software choices on F/OSS.

**Comment by iCHAIT** [comment]
I think the list already adheres to what you are suggesting, have a closer look at any of the sections and you'll see that a software has a FOSS logo at the end.

**Comment by briatte** [comment]
But free ≠ open source – unless all open source programs in the list are free, and all freeware in the list are open source ;-)

**Comment by iCHAIT** [comment]
Ah, got your point, yeah, that would be a nice addition to the list. But what should a freeware icon look like? Do you have anything in mind?

**Comment by briatte** [comment]
How about using the [Creative Commons NonCommercial](https://commons.wikimedia.org/wiki/File:Creative_Commons_%22Non-Commercial%22_icon_(SVG,_nominal_64x64).svg) icon?

Here's a modified version:

![120px-dollar_sign_in_circle barred svg](https://cloud.githubusercontent.com/assets/322533/14900425/ca568ab0-0d90-11e6-88cc-71e54c7a60b1.png)

Small preview:

![120px-dollar_sign_in_circle svg barred 14x14](https://cloud.githubusercontent.com/assets/322533/14900516/2e951366-0d91-11e6-88a2-682ad2350c1f.png)

I produced the pictures above in PNG, but it should be very easily doable in SVG.

**Comment by iCHAIT** [comment]
Yeah, that looks good to me 👍 

Can you open a PR adding the SVG of the above to the repo? Once we have the SVG in the repo I'll add the icon to all the freeware.

**Comment by briatte** [comment]
Done: #287.

**Comment by iCHAIT** [comment]
Great, Thanks :)

BTW, we'd want the size of [OSS icon](https://github.com/iCHAIT/awesome-osx/blob/master/media/oss.svg) and costless icon to be the same (for the sake of consistency), so I was wondering if the size of costless icon and OSS icon same?

**Comment by briatte** [comment]
No idea how size is calculated for SVG files, but there should be a way to both icons shown at the same size, for sure.

**Comment by iCHAIT** [comment]
I believe currently the size of the costless badge (the one in the PR you opened) is a bit bigger than the OSS one. Obviously we need not be stringent about the size of these icons being exactly same, but they should be consistent enough.

**Comment by briatte** [comment]
Let me know if you know how to adjust the size -- I can try after reinstalling Inkscape if needed!

**Comment by iCHAIT** [comment]
Unfortunately I don't, but I'll definitely try and find a solution for it soon.

**Comment by iCHAIT** [comment]
But it would be great if you could just fix it. I'll need to first install a photoshop tool as I don't currently have one on my machine :(

**Comment by briatte** [comment]
I'll give it a shot this weekend.

Otherwise, any way that the image can be constrained to a given size by some markup code in the file?

**Comment by briatte** [comment]
Oops, sorry, bad keyboard shortcut.

**Comment by iCHAIT** [comment]
Here's the [source](https://raw.githubusercontent.com/iCHAIT/awesome-osx/master/media/oss.svg) for OSS icon used in this list. It sets the width, height and viewBox as - 
 
`svg width="14px" height="14px" viewBox="0 0 14 14"`

Can you try this for the costless icon, this may work, though I am not completely sure.

**Comment by briatte** [comment]
Just submitted a PR with the resized icon. I have made the SVG as small as possible.

**Comment by briatte** [comment]
Darn, something is wrong with my PR…

**Comment by briatte** [comment]
Okay, #294 is the right PR to use. Dunno what I did wrong before.

**Comment by iCHAIT** [comment]
Thanks @briatte  for suggesting this and for opening the PR, I think this is a really nice addition to the list, I'll add the free symbol to the respective softwares in a week.
