### ISSUE TITLE
New category: Game Source Ports

### ISSUE THREAD

**Issue by alexey-lysiuk** [iCHAIT/awesome-osx#29]
Quote from Contribution Guidelines:
> New categories or improvements to the existing categorization are welcome.
There is a large number of [game source ports](https://en.wikipedia.org/wiki/Source_port) with binary builds for OS X available and regularly updated.
Does it make sense add a separate category for them? Because the source port is different from the corresponding game, it contains no copyrighted assets and data. User must own the game to play its source port.

**Comment by iCHAIT** [comment]
Hmm, I am not familiar with it so I am not very much sure about this though it does sound good.

Can you share some links (maybe 1-2) for what game source ports you are planning to put in the list?

**Comment by alexey-lysiuk** [comment]
Classic Doom:
http://www.chocolate-doom.org/
http://zdoom.org
https://zandronum.com/

Quake:
http://icculus.org/twilight/darkplaces/

Duke Nukem 3D:
http://www.eduke32.com/

**Comment by iCHAIT** [comment]
I think this particularly category does not fits well in awesome os x, but definitely goes for [awesome games](https://github.com/leereilly/games)

What do you think?
