### ISSUE TITLE
Add Awesome label

### ISSUE THREAD

**Issue by iCHAIT** [iCHAIT/awesome-osx#31]
It would be nice to have an awesome logo for this list.

Maybe something similar to [this](https://github.com/vsouza/awesome-ios/blob/master/awesome_logo.png).

**Comment by herrbischoff** [comment]
Just in case you're interested, I have created a very simple type logo with Apple's new San Francisco display font. I will send a pull request in a minute.

**Comment by iCHAIT** [comment]
Merged the PR but looks like the label is broken.

**Comment by herrbischoff** [comment]
This is weird, because you use the same kind of link for `oss.png`, which works.

    https://github.com/iCHAIT/awesome-osx/blob/master/media/oss.png

vs.

    https://github.com/iCHAIT/awesome-osx/blob/master/media/awesome.svg

**Comment by iCHAIT** [comment]
Yes, indeed I also tried using the `img tag` instaed and it still doesn't works :/

**Comment by herrbischoff** [comment]
But opening the direct link previews the file correctly. What the...?

**Comment by iCHAIT** [comment]
Looks like it has something to so with SVG's, maybe.

**Comment by herrbischoff** [comment]
It shouldn't:

<img width="877" alt="screen shot 2015-09-18 at 14 51 00" src="https://cloud.githubusercontent.com/assets/8957346/9959490/bd5c46d2-5e14-11e5-93eb-4265e25bba63.png">

**Comment by herrbischoff** [comment]
But just for the sake of it, here's the same file exported as a PNG at 3x:

![awesome](https://cloud.githubusercontent.com/assets/8957346/9959574/59e65e34-5e15-11e5-9b19-90ca81371ba4.png)

**Comment by iCHAIT** [comment]
Serving the image via rawgit makes it visible on the readme :/
It is a poor workaround though.

**Comment by herrbischoff** [comment]
So it won't even work with the PNG I uploaded above?

**Comment by iCHAIT** [comment]
I am not sure, after a little bit of googling I found this -

http://stackoverflow.com/a/21521184

Though I don't know how relevant is this now.

**Comment by herrbischoff** [comment]
I see. Good catch! So it appears to be a GitHub issue. If you want, I will open another pull request, removing the SVG and adding the PNG.

**Comment by iCHAIT** [comment]
I don't think their is really a need for it. Totally fine with SVG.

Though in case you wanted to dig a little deeper into the issue - 

https://github.com/isaacs/github/issues/316

**Comment by herrbischoff** [comment]
Interesting, thanks for the link! I will keep that in mind for future occasions.

**Comment by iCHAIT** [comment]
:+1:
