### ISSUE TITLE
Add Intellij IDEA

### ISSUE THREAD

**Issue by munendrasn** [iCHAIT/awesome-osx#316]
`IntelliJ` is Capable Java IDE with Rich features. It is best suited for productivity for Developers. Also, Lot of plugins are available and can be used as normal text editor.
Should this be added to `Developers` or `Editors` Section??

**Comment by iCHAIT** [comment]
No, [it doesn't fits into the list](https://github.com/iCHAIT/awesome-osx/pull/122).
